spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/todo_db

  redis:
    host: todo-redis
    port: 6379

logging:
  level:
    root: WARN
    com.example.todo: INFO
services:
  todo-api:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  depends_on:
    todo-redis:
      condition: service_healthy
