scrape_configs:
  - job_name: "todo-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["todo-gateway:8080"]

  - job_name: "todo-api"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["todo-api:8080"]
