server:
  port: 8080

spring:
  application:
    name: todo-gateway
  data:
    redis:
      host: redis
      port: 6379
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 1s
      routes:

        - id: prometheus-ui
          uri: http://todo-prometheus:9090
          predicates:
            - Path=/prometheus/**
          metadata:
            response-timeout: -1
        - id: todo-api-swagger
          uri: http://todo-api:8080
          predicates:
            - Path=/swagger-ui/**,/swagger-ui.html,/v3/api-docs/**


        - id: grafana-ui
          uri: http://todo-grafana:3000
          predicates:
            - Path=/grafana/**
          metadata:
            response-timeout: -1
          # Важно: никаких StripPrefix/RewritePath тут



        - id: todo-api
          uri: http://todo-api:8080
          predicates:
            - Path=/tasks/**
          filters:
            - name: Retry
              args:
                retries: 3
                methods: GET,POST,PUT,PATCH,DELETE
                series: SERVER_ERROR
                exceptions:
                    - java.io.IOException
                    - java.util.concurrent.TimeoutException
                backoff:
                    firstBackoff: 50ms
                    maxBackoff: 500ms
                    factor: 2
                timeout: 1s
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                redis-rate-limiter.requestedTokens: 1
                key-resolver: "#{@apiKeyResolver}"
            - name: CircuitBreaker
              args:
                name: todoApiCb
                fallbackUri: forward:/fallback/todo-api
resilience4j:
  circuitbreaker:
    instances:
      todoApiCb:
        registerHealthIndicator: true
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  timelimiter:
    instances:
      todoApiCb:
        timeoutDuration: 1s



management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

